<a href="https://colab.research.google.com/github/sharma18b/2drdmnp/blob/master/crossentropy_loss_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import nn
criterion = nn.CrossEntropyLoss();
# Example of target with class indices
loss = nn.CrossEntropyLoss()
print(loss)
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
print(input)
print(target)
output = loss(input, input)
print(output)
output.backward()



print(input)
print(target)
# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)

print(input)
print(target)
output = loss(input, target)
print(output)
output.backward()


CrossEntropyLoss()
tensor([[ 0.2874, -1.4834,  0.3847,  0.6024,  1.7583],
        [-0.1510, -1.2777,  0.2358, -1.6293, -0.7189],
        [ 0.0244, -0.1552, -0.4378,  1.1823,  0.7695]], requires_grad=True)
tensor([4, 4, 0])
tensor(-3.4778, grad_fn=<DivBackward1>)
tensor([[ 0.2874, -1.4834,  0.3847,  0.6024,  1.7583],
        [-0.1510, -1.2777,  0.2358, -1.6293, -0.7189],
        [ 0.0244, -0.1552, -0.4378,  1.1823,  0.7695]], requires_grad=True)
tensor([4, 4, 0])
tensor([[ 1.2171,  0.9029,  0.1255,  0.7238,  0.0707],
        [-0.6254,  0.8194, -0.9223,  2.2439, -0.7995],
        [ 0.3753,  0.3209,  0.8299,  0.6153, -0.2474]], requires_grad=True)
tensor([[0.2956, 0.1067, 0.0819, 0.3134, 0.2023],
        [0.5710, 0.1825, 0.0417, 0.0955, 0.1093],
        [0.1141, 0.2863, 0.2366, 0.3324, 0.0307]])
tensor(1.9391, grad_fn=<DivBackward1>)


In [ ]:
# Example of target with class probabilities
import torch
from torch import nn
criterion = nn.CrossEntropyLoss();
print(torch.__version__)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True).to(device)
target = torch.randn(3, 5).softmax(dim=1).to(device)

print(input)
print(target)
output = loss(input, target)
print(output)
output.backward()

1.10.0+cu111
cuda
tensor([[-1.0992, -1.1128,  3.6058, -1.3543, -2.4617],
        [ 1.1540, -0.3214, -1.7675, -1.4823, -0.2447],
        [ 0.2264,  0.8857, -0.2840,  1.2238, -1.1376]], device='cuda:0',
       grad_fn=<ToCopyBackward0>)
tensor([[0.1009, 0.5056, 0.0148, 0.2574, 0.1213],
        [0.0298, 0.1031, 0.1914, 0.6078, 0.0679],
        [0.1266, 0.0676, 0.6559, 0.1072, 0.0427]], device='cuda:0')
tensor(3.2975, device='cuda:0', grad_fn=<DivBackward1>)
